<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\AppService\Servino.Domain.AppService\Servino.Domain.AppService.csproj" />
    <ProjectReference Include="..\..\Domain\Service\Servino.Domain.Servcie\Servino.Domain.Service.csproj" />
    <ProjectReference Include="..\..\Infrastrucure\DataAccess\Servino.Infa.DataAccess.Repo.EfCore\Servino.Infa.DataAccess.Repo.EfCore.csproj" />
    <ProjectReference Include="..\..\Infrastrucure\Db\Servino.Infa.Db.SqlServer.EfCore\Servino.Infa.Db.SqlServer.EfCore.csproj" />
    <ProjectReference Include="..\..\Infrastrucure\Providers\Servino.Infra.Providers\Servino.Infra.Providers.csproj" />
  </ItemGroup>

</Project>
