<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CategoryAgg\Contracts\Service\" />
    <Folder Include="CategoryAgg\Enum\" />
    <Folder Include="ExpertHomeServiceAgg\Contracts\AppService\" />
    <Folder Include="ExpertHomeServiceAgg\Dtos\" />
    <Folder Include="ExpertHomeServiceAgg\Enum\" />
    <Folder Include="HomeServiceAgg\Contracts\AppService\" />
    <Folder Include="HomeServiceAgg\Dtos\" />
    <Folder Include="HomeServiceAgg\Enum\" />
    <Folder Include="LocationAgg\Entity\" />
    <Folder Include="LocationAgg\Enum\" />
    <Folder Include="SuggestionAgg\Contracts\Data\" />
    <Folder Include="UserAgg\Enum\" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
	</ItemGroup>

</Project>
