<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CategoryAgg\Contracts\Service\" />
    <Folder Include="CategoryAgg\Enum\" />
    <Folder Include="ExpertHomeServiceAgg\Contracts\AppService\" />
    <Folder Include="ExpertHomeServiceAgg\Dtos\" />
    <Folder Include="ExpertHomeServiceAgg\Enum\" />
    <Folder Include="HomeServiceAgg\Contracts\AppService\" />
    <Folder Include="HomeServiceAgg\Dtos\" />
    <Folder Include="HomeServiceAgg\Enum\" />
    <Folder Include="LocationAgg\Entity\" />
    <Folder Include="LocationAgg\Enum\" />
    <Folder Include="RequestAgg\Contracts\AppService\" />
    <Folder Include="RequestAgg\Contracts\Data\" />
    <Folder Include="RequestAgg\Contracts\Service\" />
    <Folder Include="RequestAgg\Dtos\" />
    <Folder Include="SuggestionAgg\Contracts\AppService\" />
    <Folder Include="SuggestionAgg\Contracts\Data\" />
    <Folder Include="SuggestionAgg\Contracts\Service\" />
    <Folder Include="SuggestionAgg\Dtos\" />
    <Folder Include="UserAgg\Enum\" />
  </ItemGroup>

</Project>
