<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CategoryAgg\Enums\" />
    <Folder Include="Exceptions\" />
    <Folder Include="ExpertHomeServiceAgg\Enums\" />
    <Folder Include="HomeServiceAgg\Enums\" />
    <Folder Include="LocationAgg\Enums\" />
    <Folder Include="RequestAgg\Enums\" />
    <Folder Include="UserAgg\Enums\" />
  </ItemGroup>

</Project>
