<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\app.Domain\app.Domain.csproj" />
    <ProjectReference Include="..\app.Application.Contracts\app.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Admins\Mappings\" />
    <Folder Include="Features\Admins\Commands\" />
    <Folder Include="Features\City\Mappings\" />
    <Folder Include="Features\Customers\Mappings\" />
    <Folder Include="Features\Experts\Mappings\" />
    <Folder Include="Features\Province\Mappings\" />
  </ItemGroup>

</Project>
