<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.Core" Version="1.8.23" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Domain\Core\Servino.Domain.Core\Servino.Domain.Core.csproj" />
    <ProjectReference Include="..\..\Providers\Servino.Infra.Providers\Servino.Infra.Providers.csproj" />
  </ItemGroup>

</Project>
