<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="IPE.SmsIr" Version="1.2.7" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\app.Domain\app.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Requests\Commands\" />
    <Folder Include="Features\Requests\Queries\" />
    <Folder Include="Features\Suggestions\Commands\" />
    <Folder Include="Features\Suggestions\Queries\" />
    <Folder Include="Features\Users\Commands\" />
    <Folder Include="Features\Users\Queries\" />
  </ItemGroup>

</Project>
